/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 * Alkalmazás kezdő képernyője
 * @author Márta Krisztián
 * @since 2022-06-29
 * @version 1.0
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setJFrameBackground();
    }
    
    /**
     * JFrame hátterének beállítása
     */
    public void setJFrameBackground() {
        getContentPane().setBackground(new java.awt.Color(177, 184, 252));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        exerciseButtonGroup = new javax.swing.ButtonGroup();
        exercise50RadioButton = new javax.swing.JRadioButton();
        exercise75RadioButton = new javax.swing.JRadioButton();
        exercise100RadioButton = new javax.swing.JRadioButton();
        quitButton = new javax.swing.JButton();
        wordsNumberSpinner = new javax.swing.JSpinner();
        testStartButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Word-pressed");
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        exercise50RadioButton.setBackground(new java.awt.Color(177, 184, 252));
        exerciseButtonGroup.add(exercise50RadioButton);
        exercise50RadioButton.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        exercise50RadioButton.setSelected(true);
        exercise50RadioButton.setText("50");
        exercise50RadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exercise50RadioButton.setFocusable(false);
        exercise50RadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exercise50RadioButton.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        getContentPane().add(exercise50RadioButton, gridBagConstraints);

        exercise75RadioButton.setBackground(new java.awt.Color(177, 184, 252));
        exerciseButtonGroup.add(exercise75RadioButton);
        exercise75RadioButton.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        exercise75RadioButton.setText("75");
        exercise75RadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exercise75RadioButton.setFocusable(false);
        exercise75RadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exercise75RadioButton.setPreferredSize(new java.awt.Dimension(100, 50));
        exercise75RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exercise75RadioButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 14);
        getContentPane().add(exercise75RadioButton, gridBagConstraints);

        exercise100RadioButton.setBackground(new java.awt.Color(177, 184, 252));
        exerciseButtonGroup.add(exercise100RadioButton);
        exercise100RadioButton.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        exercise100RadioButton.setText("100");
        exercise100RadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exercise100RadioButton.setFocusable(false);
        exercise100RadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exercise100RadioButton.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(exercise100RadioButton, gridBagConstraints);

        quitButton.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        quitButton.setForeground(new java.awt.Color(255, 0, 0));
        quitButton.setText("Kilépés");
        quitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitButton.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        getContentPane().add(quitButton, gridBagConstraints);

        wordsNumberSpinner.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        wordsNumberSpinner.setModel(new javax.swing.SpinnerNumberModel(20, 20, 200, 10));
        wordsNumberSpinner.setMinimumSize(new java.awt.Dimension(100, 100));
        wordsNumberSpinner.setPreferredSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        getContentPane().add(wordsNumberSpinner, gridBagConstraints);

        testStartButton.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        testStartButton.setText("Teszt indítása");
        testStartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        testStartButton.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        getContentPane().add(testStartButton, gridBagConstraints);

        setSize(new java.awt.Dimension(800, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exercise75RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exercise75RadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exercise75RadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton exercise100RadioButton;
    private javax.swing.JRadioButton exercise50RadioButton;
    private javax.swing.JRadioButton exercise75RadioButton;
    private javax.swing.ButtonGroup exerciseButtonGroup;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton testStartButton;
    private javax.swing.JSpinner wordsNumberSpinner;
    // End of variables declaration//GEN-END:variables
}
